apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpsserver
  namespace: cloudnative
spec:
  gateways:
  - httpsserver
  hosts:
  - httpserver-helm.26.cc
  http:
  - route:
    - destination:
        host: httpsvc.cloudnative.svc.cluster.local
        port:
          number: 80