apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpserver
spec:
  hosts:
    - httpserver-helm.26.cc
  gateways:
    - httpsserver
  http:
    - route:
        - destination:
            host: httpserver.default.svc.cluster.local
            port:
              number: 80
      fault:
        delay:
          percent: 50
          fixedDelay: 5s