apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
  name: svafly
spec:
  ingressClassName: nginx
  rules:
    - host: mod8-ssl.26.cc
      http:
        paths:
          - backend:
              service:
                name: httpsvc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - mod8-ssl.26.cc
      secretName: mod8-tls