apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-cluster-client
spec:
  ports:
  - name: etcd-cluster-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
  sessionAffinity: None
  type: ClusterIP